import type { AutomationOpportunity } from '../models/types';

/**
 * Five fully-populated mock automation opportunities spanning all 4 types.
 * Each includes complete pipeline data from submission through sprint readiness.
 */
export const mockOpportunities: AutomationOpportunity[] = [
  // ═══════════════════════════════════════════════════════════
  // 1. Invoice Processing → Intelligent Automation
  // ═══════════════════════════════════════════════════════════
  {
    id: 'OPP-001',
    processName: 'Invoice Processing & Validation',
    description: 'Automate end-to-end invoice processing including document ingestion, data extraction, validation against PO, three-way matching, and posting to ERP. Currently involves manual data entry from PDF/scanned invoices with high error rates.',
    businessUnit: 'Finance & Accounting',
    processOwner: 'Lisa Martinez',
    submittedBy: 'Ashutosh',
    submittedDate: '2026-05-15',
    currentStage: 'Sprint Ready',
    processCharacteristics: {
      isRuleBased: true,
      requiresReasoning: false,
      requiresMultiSystemOrchestration: false,
      usesGenAI: true,
      requiresDocumentUnderstanding: true,
      isWorkflowAutomation: true,
      hasAPIAvailability: true,
      requiresHumanInTheLoop: true,
      autonomyLevel: 3,
      dataType: 'Semi-Structured',
      processComplexity: 'Medium',
    },
    impact: {
      painPoints: 'Manual data entry from 2000+ invoices/month, 8% error rate, delayed payments, vendor complaints',
      timeSavingsHoursPerMonth: 120,
      costSavingsPerMonth: 8500,
      riskReduction: 'Elimination of duplicate payment risk and late payment penalties',
      qualityImprovement: 'Expected error rate reduction from 8% to <1%',
      strategicAlignment: 'High',
    },
    technical: {
      applications: ['SAP S/4HANA', 'SharePoint', 'Outlook', 'DocuSign'],
      dataSources: ['Invoice PDFs', 'PO Database', 'Vendor Master', 'GL Accounts'],
      dataType: 'Semi-Structured',
      currentAutomationLevel: 15,
    },
    metrics: {
      volumePerMonth: 2200,
      frequencyPerMonth: 22,
      manualEffortHours: 160,
      errorRatePercent: 8,
      usersImpacted: 12,
      avgProcessingTimeMinutes: 15,
    },
    priority: {
      businessPriority: 'High',
      targetTimeline: 'Q3 2026',
      complianceImpact: 'Medium',
      regulatoryRequirement: false,
    },
    classification: {
      recommendedType: 'Intelligent Automation',
      confidenceScore: 85,
      reasoning: 'Document understanding/OCR capabilities are central to this process. GenAI enhances intelligent document and data processing. Semi-Structured data requires intelligent parsing.',
      assumptions: ['Document templates are relatively standardized', 'APIs are documented and accessible for integration', 'Human review checkpoints will be available during execution'],
      alternatives: [
        { type: 'Hyperautomation/Agentic Automation', score: 52, reason: 'Could leverage agentic orchestration if autonomy requirements increase' },
        { type: 'RPA', score: 45, reason: 'Rule-based components could be handled by traditional RPA bots' },
        { type: 'Power Automate/Power Platform', score: 38, reason: 'Workflow portions could be rapidly built with Power Automate' },
      ],
      matchScores: {
        'Intelligent Automation': 85,
        'Hyperautomation/Agentic Automation': 52,
        'RPA': 45,
        'Power Automate/Power Platform': 38,
      },
    },
    qualification: {
      status: 'Qualified',
      overallScore: 92,
      checks: [
        { name: 'Minimum Volume Threshold', passed: true, details: 'Volume of 2200/month exceeds minimum threshold (50)', weight: 20 },
        { name: 'Manual Effort Justification', passed: true, details: '160 hours/month of manual effort justifies automation', weight: 20 },
        { name: 'Business Impact Assessment', passed: true, details: 'Time savings: 120h/month, Cost savings: $8,500/month', weight: 15 },
        { name: 'Data Source Availability', passed: true, details: '4 data source(s) identified', weight: 15 },
        { name: 'Application Landscape Defined', passed: true, details: '4 application(s) in scope: SAP S/4HANA, SharePoint, Outlook, DocuSign', weight: 10 },
        { name: 'Process Owner Identified', passed: true, details: 'Process owner: Lisa Martinez', weight: 10 },
        { name: 'Compliance Impact Evaluated', passed: true, details: 'Compliance impact: Medium', weight: 10 },
      ],
      missingInfo: [],
      recommendation: 'Opportunity meets qualification criteria. Proceed to scoring and discovery.',
    },
    score: {
      totalScore: 82,
      priorityBand: 'High',
      complexity: 'M',
      dimensions: { businessImpact: 88, strategicAlignment: 75, feasibility: 70, roiPotential: 90 },
      recommendedAutomationType: 'Intelligent Automation',
      ranking: 1,
    },
    discovery: {
      asIsSteps: [
        'Receive invoice via email/mail',
        'Manually open and review invoice document',
        'Key in invoice header data (vendor, date, amount)',
        'Key in line item details',
        'Look up PO in SAP',
        'Perform three-way match (PO, GR, Invoice)',
        'Flag discrepancies for review',
        'Route for approval if >$5000',
        'Post to SAP GL',
        'Archive document in SharePoint',
      ],
      processVariants: ['Credit memos', 'Foreign currency invoices', 'Recurring invoices', 'Intercompany invoices'],
      exceptions: ['Missing PO reference', 'Amount mismatch >2%', 'Vendor not in master', 'Duplicate invoice detection'],
      businessRules: ['Three-way match tolerance: ±2%', 'Approval required for invoices >$5000', 'Payment terms: Net 30/60/90', 'Tax validation per jurisdiction'],
      inputs: ['Invoice PDF/image', 'Purchase Order', 'Goods Receipt', 'Vendor Master Data'],
      outputs: ['Posted GL Entry', 'Payment Proposal', 'Exception Report', 'Audit Log'],
      systems: ['SAP S/4HANA', 'SharePoint', 'Outlook', 'DocuSign'],
      integrations: ['SAP BAPI/RFC', 'SharePoint REST API', 'MS Graph API', 'DocuSign eSignature API'],
      sla: 'Invoice processed within 48 hours of receipt',
      complianceRequirements: 'SOX compliance for financial document retention (7 years)',
      humanApprovals: ['Invoices >$5,000 require manager approval', 'Exceptions require AP analyst review'],
      dataVolume: '~2,200 invoices/month, peak during month-end close',
      peakPeriods: 'Month-end (25th-5th), Quarter-end, Year-end',
    },
    prd: {
      executiveSummary: 'Automate invoice processing to reduce manual data entry and errors.',
      userPersonas: ['AP Clerk', 'Finance Manager'],
      functionalRequirements: ['Ingest invoices', 'Extract data via Document AI', 'Three-way matching', 'Post to SAP'],
      nonFunctionalRequirements: ['Processing under 48 hours', '99.9% uptime', 'SOX Compliance'],
      acceptanceCriteria: ['Invoice extracted with 95% accuracy', 'Exception queue routes to AP Clerk'],
      outOfScope: ['Purchase Order creation', 'Payment processing'],
      dependencies: ['SAP S/4HANA APIs', 'Azure Document Intelligence'],
    },
    solution: {
      toBeSummary: 'AI-powered invoice processing pipeline using Document AI for extraction, rule-based validation engine for three-way matching, and automated SAP posting with human-in-the-loop for exceptions.',
      recommendedTechnology: 'Azure Document Intelligence + UiPath + SAP Integration Suite',
      architectureSummary: 'Cloud-based document processing pipeline with OCR/AI extraction, orchestration layer for validation and matching, direct SAP integration for posting, and exception management dashboard.',
      components: ['Document AI Extraction Service', 'Validation & Matching Engine', 'SAP Posting Module', 'Exception Management Portal', 'Audit & Compliance Logger'],
      integrations: ['Azure Blob Storage', 'Azure Document Intelligence', 'SAP S/4HANA OData', 'Power BI Dashboard'],
      humanInLoopDesign: 'Exception queue with review dashboard. Auto-escalation after 4 hours. Confidence threshold: 95% for auto-processing.',
      securityConsiderations: 'Data encryption at rest and in transit. Role-based access. Sensitive financial data handling per SOX requirements.',
      monitoringStrategy: 'Real-time processing dashboard, SLA tracking, error rate monitoring, volume trends.',
      scalabilityNotes: 'Designed for 5x volume increase. Horizontally scalable document processing.',
      estimatedEffort: '13 weeks, 2 developers + 1 BA',
    },
    businessCase: {
      implementationCost: 125000,
      annualSavings: 162000,
      annualSupportCost: 18000,
      roiPercentage: 115,
      paybackPeriodMonths: 10.4,
      npv: 233500,
      breakEvenMonths: 11,
      effortStoryPoints: 89,
      timelineWeeks: 13,
      fteReduction: 2.5,
    },
    backlogItems: [
      { jiraKey: 'AUTO-101', title: 'Document AI Model Training', description: 'Train custom extraction model on 500 sample invoices', type: 'Epic', priority: 'High', status: 'To Do', storyPoints: 21, assignee: 'Sarah R.', sprint: 'Sprint 1' },
      { jiraKey: 'AUTO-102', title: 'SAP Integration Module', description: 'Build OData connector for PO lookup and GL posting', type: 'Epic', priority: 'High', status: 'To Do', storyPoints: 34, assignee: 'Michael C.', sprint: 'Sprint 2' },
      { jiraKey: 'AUTO-103', title: 'Three-Way Match Engine', description: 'Implement rule-based matching with configurable tolerances', type: 'Story', priority: 'High', status: 'To Do', storyPoints: 13, assignee: 'Sarah R.', sprint: 'Sprint 2' },
      { jiraKey: 'AUTO-104', title: 'Exception Management Dashboard', description: 'React dashboard for manual exception review', type: 'Story', priority: 'Medium', status: 'To Do', storyPoints: 8, assignee: 'James W.', sprint: 'Sprint 3' },
      { jiraKey: 'AUTO-105', title: 'UAT & Go-Live Preparation', description: 'End-to-end testing with finance team', type: 'Task', priority: 'Medium', status: 'To Do', storyPoints: 13, assignee: 'Lisa M.', sprint: 'Sprint 4' },
    ],
    podAllocation: {
      podName: 'Intelligent Automation Lab',
      podLead: 'Sarah Rodriguez',
      teamSize: 5,
      skills: ['Document AI', 'NLP', 'Computer Vision', 'Python', 'Azure Cognitive Services'],
      currentCapacity: 55,
      assignedOpportunities: 2,
      specialization: 'Intelligent Automation',
      deliveryRisk: 'Medium',
      notes: 'Expert in document processing, OCR, and AI/ML pipelines',
    },
    sprintReadiness: {
      status: 'Sprint Ready',
      readinessScore: 100,
      gates: [
        { name: 'Classification Complete', passed: true, description: 'Automation type has been classified and accepted' },
        { name: 'L1 Qualification Passed', passed: true, description: 'Opportunity passed L1 qualification checks' },
        { name: 'Opportunity Scored', passed: true, description: 'Priority scoring has been completed' },
        { name: 'L2 Discovery Complete', passed: true, description: 'Process discovery and as-is documentation completed' },
        { name: 'SDD Complete', passed: true, description: 'Solution design document is complete' },
        { name: 'ROI Approved', passed: true, description: 'Business case approved' },
        { name: 'Pod Allocated', passed: true, description: 'Intelligent Automation Lab assigned' },
        { name: 'Compliance Cleared', passed: true, description: 'SOX compliance review completed' },
        { name: 'Backlog Items Created', passed: true, description: '5 items created in Jira' },
      ],
      blockers: [],
      targetSprintDate: '2026-07-07',
    },
    complianceChecks: [
      { name: 'Data Privacy (GDPR)', status: 'Passed', details: 'No PII processing beyond vendor contacts', checkedBy: 'Compliance Team', checkedDate: '2026-06-10' },
      { name: 'SOX Compliance', status: 'Passed', details: 'Financial controls documented and approved', checkedBy: 'Internal Audit', checkedDate: '2026-06-12' },
      { name: 'Security Review', status: 'Passed', details: 'Encryption standards met, RBAC configured', checkedBy: 'InfoSec Team', checkedDate: '2026-06-11' },
    ],
    auditTrail: [
      { id: 'AT-001', timestamp: '2026-05-15T09:00:00Z', action: 'Idea Submitted', performedBy: 'Ashutosh', role: 'Business User', details: 'Initial idea submitted for invoice automation', stage: 'Submitted' },
      { id: 'AT-002', timestamp: '2026-05-16T10:30:00Z', action: 'Classification Completed', performedBy: 'System', role: 'Automation COE Analyst', details: 'Auto-classified as Intelligent Automation (85% confidence)', stage: 'Classified' },
      { id: 'AT-003', timestamp: '2026-05-18T14:00:00Z', action: 'L1 Qualification Passed', performedBy: 'Raj Patel', role: 'Automation COE Analyst', details: 'Scored 92/100 on qualification', stage: 'Qualified' },
      { id: 'AT-004', timestamp: '2026-06-01T11:00:00Z', action: 'Sprint Readiness Certified', performedBy: 'Sarah Rodriguez', role: 'Solution Architect', details: 'All 9 gates passed', stage: 'Sprint Ready' },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 2. Employee Onboarding → Hyperautomation/Agentic
  // ═══════════════════════════════════════════════════════════
  {
    id: 'OPP-002',
    processName: 'Employee Onboarding Orchestration',
    description: 'End-to-end employee onboarding across HR, IT, Facilities, and Security. Includes provisioning accounts, assigning equipment, scheduling orientation, compliance training enrollment, and manager notifications. Requires intelligent decision-making based on role, department, and location.',
    businessUnit: 'Human Resources',
    processOwner: 'David Kim',
    submittedBy: 'Ashutosh',
    submittedDate: '2026-05-20',
    currentStage: 'Pod Allocated',
    processCharacteristics: {
      isRuleBased: false,
      requiresReasoning: true,
      requiresMultiSystemOrchestration: true,
      usesGenAI: true,
      requiresDocumentUnderstanding: false,
      isWorkflowAutomation: true,
      hasAPIAvailability: true,
      requiresHumanInTheLoop: true,
      autonomyLevel: 4,
      dataType: 'Structured',
      processComplexity: 'High',
    },
    impact: {
      painPoints: 'Average 5-day onboarding delay, missed steps in 30% of cases, poor new hire experience',
      timeSavingsHoursPerMonth: 80,
      costSavingsPerMonth: 6200,
      riskReduction: 'Eliminate compliance gaps in onboarding checklist completion',
      qualityImprovement: 'Reduce onboarding time from 5 days to same-day, 100% checklist completion',
      strategicAlignment: 'High',
    },
    technical: {
      applications: ['Workday', 'Active Directory', 'ServiceNow', 'Okta', 'Slack', 'Jira'],
      dataSources: ['HR Master Data', 'IT Asset Database', 'Org Chart', 'Role Matrix'],
      dataType: 'Structured',
      currentAutomationLevel: 25,
    },
    metrics: {
      volumePerMonth: 150,
      frequencyPerMonth: 22,
      manualEffortHours: 120,
      errorRatePercent: 30,
      usersImpacted: 45,
      avgProcessingTimeMinutes: 180,
    },
    priority: {
      businessPriority: 'Critical',
      targetTimeline: 'Q3 2026',
      complianceImpact: 'High',
      regulatoryRequirement: true,
    },
    classification: {
      recommendedType: 'Hyperautomation/Agentic Automation',
      confidenceScore: 92,
      reasoning: 'High autonomy level (4/5) indicates agentic capabilities. Process requires complex reasoning and decision-making. Multi-system orchestration needed across enterprise landscape. GenAI capabilities required for intelligent processing. High process complexity demands hyperautomation approach.',
      assumptions: ['Cross-system credentials and access policies are manageable', 'Organization has approved GenAI usage for this process domain', 'APIs are documented and accessible for integration'],
      alternatives: [
        { type: 'Intelligent Automation', score: 40, reason: 'AI/ML capabilities could enhance accuracy and throughput' },
        { type: 'Power Automate/Power Platform', score: 35, reason: 'Workflow portions could be rapidly built with Power Automate' },
        { type: 'RPA', score: 22, reason: 'Simpler sub-processes may be candidates for RPA' },
      ],
      matchScores: {
        'Hyperautomation/Agentic Automation': 92,
        'Intelligent Automation': 40,
        'Power Automate/Power Platform': 35,
        'RPA': 22,
      },
    },
    qualification: {
      status: 'Qualified',
      overallScore: 88,
      checks: [
        { name: 'Minimum Volume Threshold', passed: true, details: 'Volume of 150/month exceeds minimum threshold (50)', weight: 20 },
        { name: 'Manual Effort Justification', passed: true, details: '120 hours/month of manual effort justifies automation', weight: 20 },
        { name: 'Business Impact Assessment', passed: true, details: 'Time savings: 80h/month, Cost savings: $6,200/month', weight: 15 },
        { name: 'Data Source Availability', passed: true, details: '4 data source(s) identified', weight: 15 },
        { name: 'Application Landscape Defined', passed: true, details: '6 application(s) in scope', weight: 10 },
        { name: 'Process Owner Identified', passed: true, details: 'Process owner: David Kim', weight: 10 },
        { name: 'Compliance Impact Evaluated', passed: true, details: 'High compliance impact — regulatory review completed', weight: 10 },
      ],
      missingInfo: [],
      recommendation: 'Opportunity meets qualification criteria. Proceed to scoring and discovery.',
    },
    score: {
      totalScore: 78,
      priorityBand: 'High',
      complexity: 'XL',
      dimensions: { businessImpact: 75, strategicAlignment: 90, feasibility: 55, roiPotential: 85 },
      recommendedAutomationType: 'Hyperautomation/Agentic Automation',
      ranking: 2,
    },
    discovery: {
      asIsSteps: [
        'HR creates new hire record in Workday',
        'IT receives ServiceNow ticket for account provisioning',
        'AD account created manually',
        'Okta SSO configured for required applications',
        'Email and Slack channels provisioned',
        'Equipment ordered through procurement',
        'Facilities assigns desk/badge',
        'Manager notified via email',
        'Compliance training enrolled',
        'Orientation scheduled',
      ],
      processVariants: ['Remote hire', 'Contractor onboarding', 'Executive onboarding', 'International hire'],
      exceptions: ['Missing manager assignment', 'Role not in matrix', 'Equipment backorder', 'Visa/work permit pending'],
      businessRules: ['AD groups based on department + role', 'Equipment tier based on level', 'Badge access based on building + floor', 'Training requirements by role category'],
      inputs: ['Offer Letter', 'New Hire Form', 'Role Matrix', 'Org Chart'],
      outputs: ['Provisioned Accounts', 'Equipment Assignment', 'Onboarding Checklist', 'Welcome Package'],
      systems: ['Workday', 'Active Directory', 'ServiceNow', 'Okta', 'Slack', 'Jira'],
      integrations: ['Workday HCM API', 'Microsoft Graph API', 'ServiceNow REST API', 'Okta Admin API', 'Slack API'],
      sla: 'All provisioning complete within 4 hours of start date',
      complianceRequirements: 'SOX, HIPAA (for healthcare roles), mandatory training completion within 48 hours',
      humanApprovals: ['Manager approval for equipment upgrades', 'Security approval for elevated access'],
      dataVolume: '~150 new hires/month, peak in Q1 and Q3',
      peakPeriods: 'January (annual hiring wave), July (internship cohort)',
    },
    prd: {
      executiveSummary: 'Agentic automation for end-to-end employee onboarding orchestration across IT, HR, and Facilities.',
      userPersonas: ['HR Partner', 'New Hire', 'IT Admin', 'Hiring Manager'],
      functionalRequirements: ['Create Workday record', 'Provision AD account', 'Assign equipment', 'Schedule orientation'],
      nonFunctionalRequirements: ['Same-day provisioning', 'Audit logging of all access grants', 'Secure API access'],
      acceptanceCriteria: ['Onboarding completed automatically for standard profiles', 'Exceptions flagged to HR Partner within 1 hour'],
      outOfScope: ['Payroll setup', 'Benefits enrollment'],
      dependencies: ['Workday API', 'ServiceNow API', 'Okta API'],
    },
    solution: {
      toBeSummary: 'Agentic orchestration platform that autonomously manages the entire onboarding workflow, making intelligent decisions based on role, department, and location, with human approval checkpoints for exceptions.',
      recommendedTechnology: 'LangChain Agents + Azure Functions + Microsoft Graph + Workday APIs',
      architectureSummary: 'Multi-agent system with specialized agents for IT provisioning, facilities coordination, and HR compliance. Central orchestrator manages workflow state and escalations.',
      components: ['Orchestrator Agent', 'IT Provisioning Agent', 'Facilities Agent', 'Compliance Agent', 'Notification Service', 'Status Dashboard'],
      integrations: ['Workday HCM', 'Azure AD/Entra ID', 'ServiceNow', 'Okta', 'Slack', 'Teams'],
      humanInLoopDesign: 'Approval workflow for exceptions. Manager dashboard for status tracking. Auto-escalation after 2 hours.',
      securityConsiderations: 'Principle of least privilege for provisioning. Audit logging for all access grants. PII handling per data residency requirements.',
      monitoringStrategy: 'Real-time onboarding status dashboard, SLA compliance tracking, exception rate monitoring.',
      scalabilityNotes: 'Agent-based architecture scales horizontally. Designed for 10x volume.',
      estimatedEffort: '16 weeks, 3 developers + 1 BA + 1 ML engineer',
    },
    businessCase: {
      implementationCost: 185000,
      annualSavings: 134400,
      annualSupportCost: 24000,
      roiPercentage: 60,
      paybackPeriodMonths: 20.1,
      npv: 89500,
      breakEvenMonths: 21,
      effortStoryPoints: 144,
      timelineWeeks: 16,
      fteReduction: 2.0,
    },
    backlogItems: [
      { jiraKey: 'AUTO-201', title: 'Orchestrator Agent Framework', description: 'Build central orchestration agent with state management', type: 'Epic', priority: 'Critical', status: 'To Do', storyPoints: 34, assignee: 'Priya S.', sprint: 'Sprint 1' },
      { jiraKey: 'AUTO-202', title: 'IT Provisioning Agent', description: 'AD, Okta, and application provisioning agent', type: 'Epic', priority: 'High', status: 'To Do', storyPoints: 55, assignee: 'Priya S.', sprint: 'Sprint 2-3' },
      { jiraKey: 'AUTO-203', title: 'Workday Integration', description: 'New hire event listener and data sync', type: 'Story', priority: 'High', status: 'To Do', storyPoints: 21, assignee: 'Dev Team', sprint: 'Sprint 1' },
      { jiraKey: 'AUTO-204', title: 'Status Dashboard', description: 'Real-time onboarding progress dashboard', type: 'Story', priority: 'Medium', status: 'To Do', storyPoints: 13, assignee: 'James W.', sprint: 'Sprint 3' },
      { jiraKey: 'AUTO-205', title: 'Integration Testing', description: 'End-to-end testing across all systems', type: 'Task', priority: 'High', status: 'To Do', storyPoints: 21, assignee: 'QA Team', sprint: 'Sprint 4' },
    ],
    podAllocation: {
      podName: 'Agentic AI Squad',
      podLead: 'Priya Sharma',
      teamSize: 6,
      skills: ['LangChain', 'Multi-Agent Systems', 'GenAI', 'Python', 'Azure OpenAI'],
      currentCapacity: 40,
      assignedOpportunities: 2,
      specialization: 'Hyperautomation/Agentic Automation',
      deliveryRisk: 'Medium',
      notes: 'Specializes in agentic orchestration and multi-system AI workflows',
    },
    sprintReadiness: {
      status: 'Blocked',
      readinessScore: 78,
      gates: [
        { name: 'Classification Complete', passed: true, description: 'Classified as Hyperautomation/Agentic' },
        { name: 'L1 Qualification Passed', passed: true, description: 'Scored 88/100' },
        { name: 'Opportunity Scored', passed: true, description: 'Priority score: 78' },
        { name: 'L2 Discovery Complete', passed: true, description: 'Discovery documented' },
        { name: 'SDD Complete', passed: true, description: 'Solution design document is complete' },
        { name: 'ROI Approved', passed: true, description: 'ROI: 60%' },
        { name: 'Pod Allocated', passed: true, description: 'Agentic AI Squad assigned' },
        { name: 'Compliance Cleared', passed: false, description: 'HIPAA review pending for healthcare roles' },
        { name: 'Backlog Items Created', passed: true, description: '5 items in Jira' },
      ],
      blockers: ['Compliance Cleared: HIPAA review pending for healthcare roles'],
      targetSprintDate: '2026-07-14',
    },
    complianceChecks: [
      { name: 'Data Privacy (GDPR)', status: 'Passed', details: 'Employee PII handling reviewed and approved', checkedBy: 'DPO', checkedDate: '2026-06-05' },
      { name: 'HIPAA Review', status: 'Pending', details: 'Pending review for healthcare department roles', checkedBy: 'Compliance Team', checkedDate: '' },
      { name: 'Security Review', status: 'Passed', details: 'Privileged access management reviewed', checkedBy: 'InfoSec', checkedDate: '2026-06-08' },
    ],
    auditTrail: [
      { id: 'AT-010', timestamp: '2026-05-20T10:00:00Z', action: 'Idea Submitted', performedBy: 'Ashutosh', role: 'Business User', details: 'Employee onboarding automation idea', stage: 'Submitted' },
      { id: 'AT-011', timestamp: '2026-05-21T09:00:00Z', action: 'Classification Completed', performedBy: 'System', role: 'Automation COE Analyst', details: 'Classified as Hyperautomation (92%)', stage: 'Classified' },
      { id: 'AT-012', timestamp: '2026-06-10T16:00:00Z', action: 'Pod Allocated', performedBy: 'Raj Patel', role: 'Product Owner', details: 'Agentic AI Squad assigned', stage: 'Pod Allocated' },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 3. Data Entry Reconciliation → RPA
  // ═══════════════════════════════════════════════════════════
  {
    id: 'OPP-003',
    processName: 'Bank Statement Reconciliation',
    description: 'Daily reconciliation of bank statements against internal ledger entries. Involves downloading bank files, matching transactions, identifying discrepancies, and preparing reconciliation reports. Highly rule-based with structured data.',
    businessUnit: 'Treasury',
    processOwner: 'Angela Foster',
    submittedBy: 'Ashutosh',
    submittedDate: '2026-05-25',
    currentStage: 'Scored',
    processCharacteristics: {
      isRuleBased: true,
      requiresReasoning: false,
      requiresMultiSystemOrchestration: false,
      usesGenAI: false,
      requiresDocumentUnderstanding: false,
      isWorkflowAutomation: false,
      hasAPIAvailability: true,
      requiresHumanInTheLoop: false,
      autonomyLevel: 2,
      dataType: 'Structured',
      processComplexity: 'Low',
    },
    impact: {
      painPoints: 'Repetitive manual matching of 500+ transactions daily, reconciliation backlog, month-end stress',
      timeSavingsHoursPerMonth: 60,
      costSavingsPerMonth: 4200,
      riskReduction: 'Eliminate manual matching errors and unreconciled items',
      qualityImprovement: '100% transaction matching accuracy, same-day reconciliation',
      strategicAlignment: 'Medium',
    },
    technical: {
      applications: ['SAP', 'Bank Portal', 'Excel'],
      dataSources: ['Bank Statement Files (MT940/BAI2)', 'SAP GL', 'Cash Management Module'],
      dataType: 'Structured',
      currentAutomationLevel: 10,
    },
    metrics: {
      volumePerMonth: 12000,
      frequencyPerMonth: 22,
      manualEffortHours: 88,
      errorRatePercent: 3,
      usersImpacted: 6,
      avgProcessingTimeMinutes: 5,
    },
    priority: {
      businessPriority: 'Medium',
      targetTimeline: 'Q4 2026',
      complianceImpact: 'Low',
      regulatoryRequirement: false,
    },
    classification: {
      recommendedType: 'RPA',
      confidenceScore: 94,
      reasoning: 'Highly rule-based process ideal for robotic process automation. Structured data enables deterministic bot execution. No complex reasoning required — straightforward automation. Low autonomy requirement suits attended/unattended RPA bots.',
      assumptions: ['APIs are documented and accessible for integration'],
      alternatives: [
        { type: 'Power Automate/Power Platform', score: 62, reason: 'Workflow portions could be rapidly built with Power Automate' },
        { type: 'Intelligent Automation', score: 20, reason: 'Intelligent features could handle edge cases and exceptions' },
        { type: 'Hyperautomation/Agentic Automation', score: 12, reason: 'May benefit from agentic approach as process matures' },
      ],
      matchScores: {
        'RPA': 94,
        'Power Automate/Power Platform': 62,
        'Intelligent Automation': 20,
        'Hyperautomation/Agentic Automation': 12,
      },
    },
    qualification: {
      status: 'Qualified',
      overallScore: 85,
      checks: [
        { name: 'Minimum Volume Threshold', passed: true, details: 'Volume of 12000/month exceeds minimum threshold (50)', weight: 20 },
        { name: 'Manual Effort Justification', passed: true, details: '88 hours/month of manual effort justifies automation', weight: 20 },
        { name: 'Business Impact Assessment', passed: true, details: 'Time savings: 60h/month, Cost savings: $4,200/month', weight: 15 },
        { name: 'Data Source Availability', passed: true, details: '3 data source(s) identified', weight: 15 },
        { name: 'Application Landscape Defined', passed: true, details: '3 application(s) in scope', weight: 10 },
        { name: 'Process Owner Identified', passed: true, details: 'Process owner: Angela Foster', weight: 10 },
        { name: 'Compliance Impact Evaluated', passed: true, details: 'Compliance impact: Low', weight: 10 },
      ],
      missingInfo: [],
      recommendation: 'Opportunity meets qualification criteria. Proceed to scoring and discovery.',
    },
    score: {
      totalScore: 65,
      priorityBand: 'Medium',
      complexity: 'S',
      dimensions: { businessImpact: 70, strategicAlignment: 45, feasibility: 90, roiPotential: 60 },
      recommendedAutomationType: 'RPA',
      ranking: 3,
    },
    discovery: null,
    prd: null,
    solution: null,
    businessCase: null,
    backlogItems: [],
    podAllocation: null,
    sprintReadiness: null,
    complianceChecks: [],
    auditTrail: [
      { id: 'AT-020', timestamp: '2026-05-25T11:00:00Z', action: 'Idea Submitted', performedBy: 'Ashutosh', role: 'Business User', details: 'Bank reconciliation automation', stage: 'Submitted' },
      { id: 'AT-021', timestamp: '2026-05-26T08:30:00Z', action: 'Classification Completed', performedBy: 'System', role: 'Automation COE Analyst', details: 'Classified as RPA (94%)', stage: 'Classified' },
      { id: 'AT-022', timestamp: '2026-05-28T15:00:00Z', action: 'Scoring Completed', performedBy: 'System', role: 'Automation COE Analyst', details: 'Score: 65 (Medium priority)', stage: 'Scored' },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 4. IT Helpdesk Ticket Routing → Intelligent Automation
  // ═══════════════════════════════════════════════════════════
  {
    id: 'OPP-004',
    processName: 'IT Helpdesk Ticket Triage & Routing',
    description: 'Automated classification, priority assignment, and routing of IT support tickets using NLP and GenAI. Includes sentiment analysis, category prediction, SLA assignment, and intelligent routing to the appropriate support group. Human review for edge cases.',
    businessUnit: 'IT Service Management',
    processOwner: 'Robert Chang',
    submittedBy: 'Ashutosh',
    submittedDate: '2026-06-01',
    currentStage: 'Qualified',
    processCharacteristics: {
      isRuleBased: false,
      requiresReasoning: true,
      requiresMultiSystemOrchestration: false,
      usesGenAI: true,
      requiresDocumentUnderstanding: false,
      isWorkflowAutomation: true,
      hasAPIAvailability: true,
      requiresHumanInTheLoop: true,
      autonomyLevel: 3,
      dataType: 'Unstructured',
      processComplexity: 'Medium',
    },
    impact: {
      painPoints: 'Average 4-hour ticket assignment delay, 25% misrouting rate, inconsistent priority assignment',
      timeSavingsHoursPerMonth: 45,
      costSavingsPerMonth: 3800,
      riskReduction: 'Reduce SLA breaches from 15% to <3%',
      qualityImprovement: 'Consistent categorization and routing, reduced resolution time',
      strategicAlignment: 'Medium',
    },
    technical: {
      applications: ['ServiceNow', 'Teams', 'Knowledge Base'],
      dataSources: ['Ticket History (3 years)', 'Knowledge Base Articles', 'SLA Matrix', 'Support Group Directory'],
      dataType: 'Unstructured',
      currentAutomationLevel: 20,
    },
    metrics: {
      volumePerMonth: 3500,
      frequencyPerMonth: 22,
      manualEffortHours: 65,
      errorRatePercent: 25,
      usersImpacted: 2500,
      avgProcessingTimeMinutes: 8,
    },
    priority: {
      businessPriority: 'High',
      targetTimeline: 'Q4 2026',
      complianceImpact: 'Low',
      regulatoryRequirement: false,
    },
    classification: {
      recommendedType: 'Intelligent Automation',
      confidenceScore: 80,
      reasoning: 'GenAI enhances intelligent document and data processing. Unstructured data requires intelligent parsing. Cognitive reasoning needed for exception handling.',
      assumptions: ['Organization has approved GenAI usage for this process domain', 'Human review checkpoints will be available during execution'],
      alternatives: [
        { type: 'Hyperautomation/Agentic Automation', score: 58, reason: 'Could leverage agentic orchestration if autonomy requirements increase' },
        { type: 'Power Automate/Power Platform', score: 32, reason: 'Workflow portions could be rapidly built with Power Automate' },
        { type: 'RPA', score: 18, reason: 'Simpler sub-processes may be candidates for RPA' },
      ],
      matchScores: {
        'Intelligent Automation': 80,
        'Hyperautomation/Agentic Automation': 58,
        'Power Automate/Power Platform': 32,
        'RPA': 18,
      },
    },
    qualification: {
      status: 'Qualified',
      overallScore: 80,
      checks: [
        { name: 'Minimum Volume Threshold', passed: true, details: 'Volume of 3500/month exceeds minimum threshold', weight: 20 },
        { name: 'Manual Effort Justification', passed: true, details: '65 hours/month of manual effort', weight: 20 },
        { name: 'Business Impact Assessment', passed: true, details: 'Time savings: 45h/month, Cost savings: $3,800/month', weight: 15 },
        { name: 'Data Source Availability', passed: true, details: '4 data source(s) identified', weight: 15 },
        { name: 'Application Landscape Defined', passed: true, details: '3 application(s) in scope', weight: 10 },
        { name: 'Process Owner Identified', passed: true, details: 'Process owner: Robert Chang', weight: 10 },
        { name: 'Compliance Impact Evaluated', passed: true, details: 'Compliance impact: Low', weight: 10 },
      ],
      missingInfo: [],
      recommendation: 'Opportunity meets qualification criteria. Proceed to scoring and discovery.',
    },
    score: null,
    discovery: null,
    prd: null,
    solution: null,
    businessCase: null,
    backlogItems: [],
    podAllocation: null,
    sprintReadiness: null,
    complianceChecks: [],
    auditTrail: [
      { id: 'AT-030', timestamp: '2026-06-01T09:00:00Z', action: 'Idea Submitted', performedBy: 'Ashutosh', role: 'Business User', details: 'IT helpdesk automation idea', stage: 'Submitted' },
      { id: 'AT-031', timestamp: '2026-06-02T10:00:00Z', action: 'Classification Completed', performedBy: 'System', role: 'Automation COE Analyst', details: 'Classified as Intelligent Automation (80%)', stage: 'Classified' },
      { id: 'AT-032', timestamp: '2026-06-05T14:00:00Z', action: 'L1 Qualification Passed', performedBy: 'Raj Patel', role: 'Automation COE Analyst', details: 'Scored 80/100', stage: 'Qualified' },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 5. Expense Report Approval → Power Automate/Power Platform
  // ═══════════════════════════════════════════════════════════
  {
    id: 'OPP-005',
    processName: 'Expense Report Approval Workflow',
    description: 'Streamline expense report submission, policy validation, manager approval routing, and finance posting. Currently managed through email chains and Excel tracking sheets. Simple workflow with clear business rules and available APIs.',
    businessUnit: 'Finance',
    processOwner: 'Jennifer Adams',
    submittedBy: 'Ashutosh',
    submittedDate: '2026-06-05',
    currentStage: 'Classified',
    processCharacteristics: {
      isRuleBased: true,
      requiresReasoning: false,
      requiresMultiSystemOrchestration: false,
      usesGenAI: false,
      requiresDocumentUnderstanding: false,
      isWorkflowAutomation: true,
      hasAPIAvailability: true,
      requiresHumanInTheLoop: true,
      autonomyLevel: 2,
      dataType: 'Structured',
      processComplexity: 'Low',
    },
    impact: {
      painPoints: 'Manual email-based approvals take 3-5 days, lost receipts, policy violations detected post-facto',
      timeSavingsHoursPerMonth: 30,
      costSavingsPerMonth: 2100,
      riskReduction: 'Real-time policy enforcement prevents out-of-policy expenses',
      qualityImprovement: 'Approval turnaround reduced from 5 days to 4 hours',
      strategicAlignment: 'Low',
    },
    technical: {
      applications: ['SAP Concur', 'Outlook', 'SharePoint'],
      dataSources: ['Expense Policy Rules', 'Employee Directory', 'Cost Center Data'],
      dataType: 'Structured',
      currentAutomationLevel: 5,
    },
    metrics: {
      volumePerMonth: 800,
      frequencyPerMonth: 22,
      manualEffortHours: 40,
      errorRatePercent: 12,
      usersImpacted: 200,
      avgProcessingTimeMinutes: 10,
    },
    priority: {
      businessPriority: 'Low',
      targetTimeline: 'Q1 2027',
      complianceImpact: 'Low',
      regulatoryRequirement: false,
    },
    classification: {
      recommendedType: 'Power Automate/Power Platform',
      confidenceScore: 90,
      reasoning: 'Workflow-centric process fits Power Automate cloud flows. Existing API connectors enable rapid Power Platform integration. Low complexity suitable for citizen-developer Power Apps.',
      assumptions: ['APIs are documented and accessible for integration', 'Human review checkpoints will be available during execution'],
      alternatives: [
        { type: 'RPA', score: 68, reason: 'Rule-based components could be handled by traditional RPA bots' },
        { type: 'Intelligent Automation', score: 22, reason: 'Intelligent features could handle edge cases and exceptions' },
        { type: 'Hyperautomation/Agentic Automation', score: 10, reason: 'May benefit from agentic approach as process matures' },
      ],
      matchScores: {
        'Power Automate/Power Platform': 90,
        'RPA': 68,
        'Intelligent Automation': 22,
        'Hyperautomation/Agentic Automation': 10,
      },
    },
    qualification: null,
    score: null,
    discovery: null,
    prd: null,
    solution: null,
    businessCase: null,
    backlogItems: [],
    podAllocation: null,
    sprintReadiness: null,
    complianceChecks: [],
    auditTrail: [
      { id: 'AT-040', timestamp: '2026-06-05T13:00:00Z', action: 'Idea Submitted', performedBy: 'Ashutosh', role: 'Business User', details: 'Expense report automation', stage: 'Submitted' },
      { id: 'AT-041', timestamp: '2026-06-06T09:30:00Z', action: 'Classification Completed', performedBy: 'System', role: 'Automation COE Analyst', details: 'Classified as Power Platform (90%)', stage: 'Classified' },
    ],
  },
];
